language: go

install:
  - go get -t ./...
  - git clone https://github.com/sstephenson/bats.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - go install github.com/bamarni/ticketfile/cmd/ticket

script:
  - go test -v ./...
  - bats --version
  - bats tests/functional

notifications:
  email: false
