language: go

install:
  - go get golang.org/x/text/encoding
  - git clone https://github.com/sstephenson/bats.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - (cd tests/integration && go build printer.go)
  - export PATH=/tmp/local/bin:$PWD/tests/integration:$PATH

script:
  - bats --version
  - bats tests/integration

notifications:
  email: false
